# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: required
cache: packages

r:
  - oldrel
  - release
  - devel

r_packages:
  - devtools
  - methods
  - XML
  - RCurl
  - plyr
  - utils
  - testthat

r_build_args: --no-manual
r_check_args: --no-manual --no-build-vignettes --as-cran

after_success:
  - Rscript -e 'devtools::install_github("jimhester/covr")'
  - Rscript -e 'library(covr); codecov()'

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
